### PR TITLE
Remove the push Registration Screen

### PR DESCRIPTION
**Pull request by danielpassos**
Related issues:

* [AEROGEAR-3069](https://issues.jboss.org/browse/AEROGEAR-3069)

### CODE REVIEW

**Comment by wei-lee** [comment]
I can see there is no registration page anymore. 

@ciaranRoche not sure I understand your comment.

**Comment by laurafitzgerald** [comment]
@ciaranRoche the trello card was [updated](https://trello.com/c/Gl3kGI8w/97-1-push-register-screen-as-an-end-user-i-want-the-push-registration-to-happen-automatically-on-app-startup) based on the comments/feedback.. The JIRAs should have been updated. I will do that now. Sorry for confusion

**Comment by laurafitzgerald** [comment]
the push registration screen only exists in Android so the other JIRAs should have been closed. Will close them now.

**Comment by ciaranRoche** [comment]
@wei-lee Pretty much what Laura said, I got some confusion based on the JIRA's

**Pull request merged**
