### PR TITLE
Add lading screen

### PR DESCRIPTION
**Pull request by danielpassos**
Related issues:

* [AEROGEAR-3033](https://issues.jboss.org/browse/AEROGEAR-3033)

| Identity Manager | Security | Push | Metrics |
|---|---|---|---|
|screenshot-1529586682443|screenshot-1529586687514|screenshot-1529586935542|screenshot-1529586940913|

### CODE REVIEW

**Comment by wei-lee** [comment]
@danielpassos can we make the bullet points aligned properly?

**Comment by danielpassos** [comment]
@wei-lee is that ok now?!

| Identity Manager | Security | Push | Metrics |
|---|---|---|---|
|screenshot-1529588783332|screenshot-1529588787399|screenshot-1529588792673|screenshot-1529588797700|

**Comment by wei-lee** [comment]
@danielpassos not really. If you look at other platforms, the text are aligned when there are multiple lines. But it is different on Android.

**Comment by danielpassos** [comment]
@wei-lee do you mean all the lines should start after the bullet point space?

**Comment by wei-lee** [comment]
@danielpassos yes

**Comment by danielpassos** [comment]
@wei-lee Is this what do you want?

| Identity Manager | Security | Push | Metrics |
|---|---|---|---|
|screenshot_1529597387|screenshot_1529597391|screenshot_1529597396|screenshot_1529597403|

**Comment by wei-lee** [comment]
@danielpassos yes 👍

**Pull request merged**
