### PR TITLE
authentication details page update

### PR DESCRIPTION
**Pull request by StephenCoady**
## Motivation

JIRA: https://issues.jboss.org/browse/AEROGEAR-2971

## Screenshot
screenshot 2018-06-21 16 26 13

### CODE REVIEW

**Comment by StephenCoady** [comment]
@danielpassos @wei-lee @secondsun mind taking a look?

**Comment by wei-lee** [comment]
👀

**Comment by wei-lee** [comment]
what @ciaranRoche said. Otherwise looks good.

**Comment by StephenCoady** [comment]
ping @wei-lee @ciaranRoche updated now, good to merge?

**Pull request merged**
