### PR TITLE
Update menu

### PR DESCRIPTION
**Pull request by danielpassos**
Related issues:

* [AEROGEAR-2959](https://issues.jboss.org/browse/AEROGEAR-2959)

| Under Construction | Menu |
|---|---|
|screenshot-1529435822711|screenshot_1529441364|

### CODE REVIEW

**Comment by danielpassos** [comment]
@wei-lee I have no idea what I should link on:

* Device Profile Info
* Trust Check Info

**Comment by wei-lee** [comment]
@danielpassos They can be linked to "Under Construction" page for now.

**Comment by wei-lee** [comment]
@secondsun Are you talking about the ones with icons in the menu? They are supposed to open the "landing page" for each service.

**Comment by danielpassos** [comment]
@wei-lee @secondsun I have updated the header and the menu screenshot!

**Comment by secondsun** [comment]
@wei-lee Ahhh right.  I think I just brain farted.

For future me, here is the JIRA : AEROGEAR-3033

**Comment by danielpassos** [comment]
@wei-lee What should I use in SSO menu item? I just saw @secondsun removed the [Access control](https://github.com/aerogear/android-showcase-template/pull/42) and I was using it on SSO

**Pull request merged**
