### PR TITLE
AEROGEAR-3564 - use #nochrome link to hide navbar on docs

### PR DESCRIPTION
**Pull request by jasonmadigan**
## Motivation

JIRA: https://issues.jboss.org/browse/AEROGEAR-3564

waiting for https://github.com/aerogear/antora-ui/pull/13 to be deployed to docs.aerogear.org - change will become visible then (I hope!)

### CODE REVIEW

**Comment by danielpassos** [comment]
@jasonmadigan  `#nochrome` does not work on my phone!

screenshot_20180702-183459

**Comment by jasonmadigan** [comment]
@laurafitzgerald @aidenkeating changes enabling this to be tested in aerogear/antora-ui#13 have been landed. Should be OK to do a quick test now?

**Comment by secondsun** [comment]
@jasonmadigan Does not work in my emulator, there is a error in log cat : "Denied starting an intent without a user gesture, URI https://docs.aerogear.org/aerogear/latest/identity-management.html?header=false" and in the ui the emulator  just shows a white screen.

recent:///b830f6735c6307fa75c0f7db5b3bc29b

**Comment by secondsun** [comment]
It seems like the error is that the website tries to redirect itself into a new window when the webview opens it.  This new window would be opened with the system browser instead of a web view.  Since this behavior is automatic Android P (and perhaps earlier) blocks it.  I tested it on Android L and it does redirect out of the app.

I am assuming redirects out of the app are not wanted.

**Comment by secondsun** [comment]
```fix.path
From 5136f96af6f05b351dbc9c905dee4d396b33dba4 Mon Sep 17 00:00:00 2001
From: Summers Pittman <secondsun@gmail.com>
Date: Tue, 3 Jul 2018 14:44:42 -0400
Subject: [PATCH] Webview works again

---
 .../features/documentation/DocumentationFragment.java  | 10 ++++++++++
 1 file changed, 10 insertions(+)

diff --git a/app/src/main/java/com/aerogear/androidshowcase/features/documentation/DocumentationFragment.java b/app/src/main/java/com/aerogear/androidshowcase/features/documentation/DocumentationFragment.java
index 0f07b14..849b0b1 100644
--- a/app/src/main/java/com/aerogear/androidshowcase/features/documentation/DocumentationFragment.java
+++ b/app/src/main/java/com/aerogear/androidshowcase/features/documentation/DocumentationFragment.java
@@ -6,7 +6,9 @@ import android.support.annotation.Nullable;
 import android.view.LayoutInflater;
 import android.view.View;
 import android.view.ViewGroup;
+import android.webkit.WebResourceRequest;
 import android.webkit.WebView;
+import android.webkit.WebViewClient;
 
 import com.aerogear.androidshowcase.features.documentation.presenters.DocumentationPresenter;
 import com.aerogear.androidshowcase.features.documentation.views.DocumentationView;
@@ -77,6 +79,14 @@ public class DocumentationFragment extends BaseFragment<DocumentationPresenter,
     public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, Bundle savedInstanceState) {
         WebView webview = new WebView(this.getActivity());
 
+        webview.setWebViewClient(new WebViewClient() {
+            @Override
+            public boolean shouldOverrideUrlLoading(WebView view, WebResourceRequest request) {
+                view.loadUrl(request.getUrl().toString());
+                return false;
+            }
+        });
+
         webview.getSettings().setJavaScriptEnabled(true);
         webview.loadUrl(this.url);
 
-- 
2.17.1
```

**Comment by secondsun** [comment]
recent:///32d748d70b46defef3605f805b3bc461

**Comment by secondsun** [comment]
image

**Comment by wei-lee** [comment]
@jasonmadigan If you merge this PR: https://github.com/jasonmadigan/android-showcase-template/pull/2 and rebase, we can merge this PR.

**Comment by wei-lee** [comment]
replaced by #60

**Pull request closed without merging**
