### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by danielpassos**
# Replace default TextView color from gray to black 

| Before | After  |
|---|---|
|screenshot-1528981234748|screenshot-1528982443581|

# Disable all caps for buttons 

| Before | After  |
|---|---|
|screenshot-1528982249915|screenshot-1528982209179|

# Replace default TextView color from gray to black

### CODE REVIEW

**Comment by secondsun** [comment]
@danielpassos can I get a rebase?

**Comment by danielpassos** [comment]
@secondsun Rebased.

**Comment by secondsun** [comment]
Landed @ 72f0d3c

**Comment by secondsun** [comment]
(Github didn't pick up the merge correctly)

**Pull request closed without merging**
