### PR TITLE
Add Device Metrics

### PR DESCRIPTION
**Pull request by TommyJ1994**
**Description**

Metrics weren't added before, adding them here. Also removing old checks.

Jira - https://issues.jboss.org/browse/AGDROID-812

- [x] Add Device Metrics - https://github.com/aerogear/android-showcase-template/commit/7addd008459656c9a2f3ace258a3a8d8ea9f179f

### CODE REVIEW

**Comment by TommyJ1994** [comment]
Ping @psturc

**Comment by wtrocki** [comment]
ping @danielpassos @secondsun

**Comment by wtrocki** [comment]
Mentioned as blocker.

**Comment by psturc** [comment]
Blocked by https://issues.jboss.org/browse/AGDROID-813

**Pull request merged**
